### ISSUE TITLE
Usar rem units en vez de em units para font-sizes

### ISSUE THREAD

**Issue by AGutierrezR** [deividcode/sign-up-form#1]
En el CSS es buena practica usar `rem`s para establecer el `font-size` del texto. El uso de `em`s es mas recomendado para otro tipo de medidas (`padding`s normalmente, aunque de principio es un poco extraño, por eso usa `rem` tambien).

Si quieres ser bastante explicito, puedes establecer el `font-size` el `html` a `16px` (el valor por defecto) y hacer que el `body` sea `1rem`

```css
html {
  font-size: 16px;
}

body {
  position:relative;
  font-family: 'Montserrat', sans-serif;
  font-size: 1rem;
}
```

A pesar de ser los valores por defecto, es buena practica dejarlo para que sea mas explicito (este es uno de los pocos casos). 

Si estas usando VSCode, puedes descargar una extension llamada **px to rem & rpx & vw (cssrem)** que te ayuda a hacer la conversión mucho mas facil
