### ISSUE TITLE
Usar CSS Custom properties (variables) para almacenar los colores

### ISSUE THREAD

**Issue by AGutierrezR** [deividcode/sign-up-form#2]
Podrías usar variables de CSS para almacenar los colores y no tener que hacer referencia a los colores recordan el valor hex.

Por ejemplo:

```css
:root {
  --color-1: #03C988;
  --color-2: #03c987b7;
  --color-3: #ff0000d1;
  --color-4: #202020b8;
  --color-5: #202020a8;
  --color-6: #00000099;
  --color-7: #00000061;
  --color-8: #a9aeb3;
  --color-9: #2020204d;
  --color-10: #0000004f;
  --color-11: #202020;
  --color-12: #fff;
}
```

Podrías cambiar los números (1, 2, 3,...) por el nombre de la variable, algo asi:

```css
:root {
  --color-green-1: #03C988;
  --color-green-2: #03c987b7;
  --color-red-: #ff0000d1;
  --color-black-100: #202020b8;
  --color-black-200: #202020a8;
  --color-black-300: #00000099;
  --color-black-400: #00000061;
  --color-black-500: #a9aeb3;
  --color-black-600: #2020204d;
  --color-black-700: #0000004f;
  --color-black-800: #202020;
  --color-white: #fff;
}
```

Y usar las variables con `var(--color-XXX);`
